<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>community.flock.wirespec.example.maven</groupId>
        <artifactId>maven-spring-custom</artifactId>
        <version>0.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>extension</artifactId>

    <dependencies>
        <dependency>
            <groupId>community.flock.wirespec.compiler</groupId>
            <artifactId>core-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>community.flock.wirespec.ir</groupId>
            <artifactId>ir-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
