GET http://localhost:8080/todos
Accept: application/json

###

GET http://localhost:8080/todos/8132b795-143f-4afb-8c8a-0608cb63c79c
Accept: application/json

###

POST http://localhost:8080/todos
Content-Type: application/json

{
  "name": "Difficult Task",
  "done": false
}

###

DELETE http://localhost:8080/todos/8132b795-143f-4afb-8c8a-0608cb63c79c
Content-Type: application/json

###
