package community.flock.wirespec.integration.kotest.dsl

import community.flock.wirespec.integration.kotest.generator.KotestWirespecGeneratorBuilder
import community.flock.wirespec.integration.kotest.generator.kotestWirespecKotlinGenerator
import community.flock.wirespec.kotlin.Wirespec
import io.kotest.property.RandomSource
import java.lang.reflect.Method
import java.util.concurrent.ConcurrentHashMap

/** Per-call holder of the kotest-backed [Wirespec.Generator] plus a cache of the generated `*Generator` adapters. */
class ArbReceiver internal constructor(private val randomSource: RandomSource) {

    @PublishedApi
    internal val generator: Wirespec.Generator =
        kotestWirespecKotlinGenerator(seed = randomSource.random.nextLong())

    @Suppress("UNCHECKED_CAST")
    internal fun <T> generateModel(
        modelClass: Class<*>,
        overrides: (KotestWirespecGeneratorBuilder.() -> Unit)? = null,
    ): T {
        val generator = overrides
            ?.let { kotestWirespecKotlinGenerator(seed = randomSource.random.nextLong(), block = it) }
            ?: this.generator
        return generatorFor(modelClass).generate(generator, emptyList()) as T
    }

    /** Locate (and cache) the IR-emitted `<Model>Generator` for [modelClass]. */
    @PublishedApi
    internal fun generatorFor(modelClass: Class<*>): GeneratorHandle = cache.computeIfAbsent(modelClass) {
        val modelPkg = modelClass.`package`?.name
            ?: error("${modelClass.simpleName}: no package; was this class actually generated by Wirespec?")
        val generatorName = "${modelPkg.removeSuffix(".model")}.generator.${modelClass.simpleName}Generator"
        val cls = runCatching { Class.forName(generatorName, true, modelClass.classLoader) }.getOrElse {
            error(
                "Could not locate $generatorName for ${modelClass.simpleName}. The Wirespec IR Kotlin emitter " +
                    "must be enabled (emitterClass = KotlinIrEmitter::class.java) so per-type generators are emitted.",
            )
        }
        val instance = cls.getDeclaredField("INSTANCE").get(null)
        val method = cls.declaredMethods.firstOrNull { it.name == "generate" && it.parameterCount == 2 }
            ?: error("$generatorName has no `generate(generator, path)` method — unexpected shape.")
        GeneratorHandle(instance, method)
    }

    @PublishedApi
    internal class GeneratorHandle(private val instance: Any, private val generateMethod: Method) {
        fun generate(generator: Wirespec.Generator, path: List<String>): Any = generateMethod.invoke(instance, generator, path)
    }

    private companion object {
        val cache = ConcurrentHashMap<Class<*>, GeneratorHandle>()
    }
}
