package community.flock.wirespec.integration.kotest.dsl

import community.flock.wirespec.integration.kotest.kotestWirespecKotlinGenerator
import community.flock.wirespec.kotlin.Wirespec
import io.kotest.property.RandomSource
import java.lang.reflect.Method
import java.util.concurrent.ConcurrentHashMap

/**
 * Per-call holder of the kotest-backed [Wirespec.Generator] plus a cache of the
 * generated `*Generator` adapters.
 *
 * Re-exposes the `kotestWirespecKotlinGenerator` adapter: every generated
 * `*Generator` (e.g. `SupplierGenerator`) walks the Wirespec IR and dispatches into
 * a [Wirespec.Generator] backed by kotest `Arb`s. This receiver does *not* reinvent
 * generation; it just makes generator lookup ergonomic for the runtime.
 *
 * The per-iteration [RandomSource] threads into the generator's seed so failures are
 * reproducible (kotest-property prints the seed on failure).
 */
class ArbReceiver internal constructor(randomSource: RandomSource) {

    /** The kotest-backed [Wirespec.Generator] used by every `*Generator.generate(...)`. */
    @PublishedApi
    internal val generator: Wirespec.Generator =
        kotestWirespecKotlinGenerator(seed = randomSource.random.nextLong())

    /** Locate (and cache) the IR-emitted `<Model>Generator` for [modelClass]. */
    @PublishedApi
    internal fun generatorFor(modelClass: Class<*>): GeneratorHandle = cache.computeIfAbsent(modelClass) {
        // Generated package convention from the Wirespec IR emitter:
        //   <root>.model.<X>               → the user-facing type
        //   <root>.generator.<X>Generator → the IR-emitted Arb adapter
        val modelPkg = modelClass.`package`?.name
            ?: error("${modelClass.simpleName}: no package; was this class actually generated by Wirespec?")
        val generatorName = "${modelPkg.removeSuffix(".model")}.generator.${modelClass.simpleName}Generator"
        val cls = runCatching { Class.forName(generatorName, true, modelClass.classLoader) }.getOrElse {
            error(
                "Could not locate $generatorName for ${modelClass.simpleName}. The Wirespec IR Kotlin emitter " +
                    "must be enabled (emitterClass = KotlinIrEmitter::class.java) so per-type generators are emitted.",
            )
        }
        val instance = cls.getDeclaredField("INSTANCE").get(null)
        val method = cls.declaredMethods.firstOrNull { it.name == "generate" && it.parameterCount == 2 }
            ?: error("$generatorName has no `generate(generator, path)` method — unexpected shape.")
        GeneratorHandle(instance, method)
    }

    @PublishedApi
    internal class GeneratorHandle(private val instance: Any, private val generateMethod: Method) {
        fun generate(generator: Wirespec.Generator, path: List<String>): Any = generateMethod.invoke(instance, generator, path)
    }

    private companion object {
        val cache = ConcurrentHashMap<Class<*>, GeneratorHandle>()
    }
}
