import org.gradle.api.tasks.testing.Test

// Codegen + updater tasks for emitter test fixtures.
//
// Each emitter test asserts against `EmitterFixtures.<testName>` constants. Those
// constants are generated from .txt files in the shared :src:compiler:test/fixtures
// directory, keyed by test name + language. The per-emitter `UpdateEmitterFixtures`
// JVM main (which actually runs the emitter and overwrites the .txt files) is also
// generated by this plugin from the `emitterFixtures { ... }` config.
//
// Apply alongside the Kotlin Multiplatform plugin and configure via:
//
//     emitterFixtures {
//         language = "java"
//         emitterPackage = "community.flock.wirespec.emitters.java"
//         emitterClass = "JavaIrEmitter"
//         generatorClass = "community.flock.wirespec.ir.generator.JavaGenerator"
//         includesTestEmitterFixtures = true
//         emitterAcceptsEmitShared = true
//         sharedOutputStyle = "generator"
//     }
//
// The emitter's build.gradle.kts wires the two generated source dirs into the
// appropriate source sets (one line each) — see `commonTest`/`jvmTest` srcDir
// hookups in the existing emitter modules.

val ext = extensions.create<EmitterFixturesExtension>("emitterFixtures")

val fixturesSourceDir = rootProject.layout.projectDirectory.dir("src/compiler/test/fixtures").asFile
val generatedSourcesDir = layout.buildDirectory.dir("generated/emitterFixtures/commonTest/kotlin")
val generatedUpdaterDir = layout.buildDirectory.dir("generated/emitterFixtures/jvmTest/kotlin")

// -------------- generateEmitterFixtures (commonTest constants) --------------

tasks.register("generateEmitterFixtures") {
    description = "Generate Kotlin constants from emitter fixture files."
    group = "build"

    // Capture locals so the action closure doesn't reference script-level state
    // (which the configuration cache cannot serialize).
    val fixturesDir = fixturesSourceDir
    val outDirProvider = generatedSourcesDir
    val languageProvider = ext.language
    val packageProvider = ext.emitterPackage

    inputs.dir(fixturesDir).withPropertyName("fixtures").optional(true)
    inputs.property("language", languageProvider)
    inputs.property("package", packageProvider)
    outputs.dir(outDirProvider).withPropertyName("generatedSources")

    doLast {
        fun escapeKotlinString(s: String): String = buildString(s.length + 16) {
            for (ch in s) {
                when (ch) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '$' -> append("\\\$")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> if (ch.code < 0x20) {
                        append("\\u")
                        append(ch.code.toString(16).padStart(4, '0'))
                    } else {
                        append(ch)
                    }
                }
            }
        }

        val language = languageProvider.get()
        val packageName = packageProvider.get()
        val outFile = outDirProvider.get().asFile
            .resolve(packageName.replace('.', '/'))
            .resolve("EmitterFixtures.kt")
        outFile.parentFile.mkdirs()

        val sb = StringBuilder()
        sb.appendLine("// AUTO-GENERATED — do not edit. Run `:updateEmitterFixtures` to refresh.")
        sb.appendLine("@file:Suppress(\"ktlint\", \"MaxLineLength\")")
        sb.appendLine("package $packageName")
        sb.appendLine()
        sb.appendLine("internal object EmitterFixtures {")

        val dirs = fixturesDir.listFiles { f -> f.isDirectory }
            ?.sortedBy { it.name }
            .orEmpty()
        for (dir in dirs) {
            val file = dir.resolve("$language.txt")
            if (!file.exists()) continue
            val literal = escapeKotlinString(file.readText().replace("\r\n", "\n"))
            sb.appendLine("    val ${dir.name}: String = \"$literal\"")
        }
        sb.appendLine("}")
        outFile.writeText(sb.toString())
    }
}

// -------------- generateUpdateEmitterFixtures (jvmTest main) --------------

tasks.register("generateUpdateEmitterFixtures") {
    description = "Generate the per-emitter UpdateEmitterFixtures main()."
    group = "build"

    val outDirProvider = generatedUpdaterDir
    val languageProvider = ext.language
    val packageProvider = ext.emitterPackage
    val emitterClassProvider = ext.emitterClass
    val generatorClassProvider = ext.generatorClass
    val includesNodeFixturesProvider = ext.includesTestEmitterFixtures
    val acceptsEmitSharedProvider = ext.emitterAcceptsEmitShared
    val sharedStyleProvider = ext.sharedOutputStyle

    inputs.property("language", languageProvider)
    inputs.property("package", packageProvider)
    inputs.property("emitterClass", emitterClassProvider)
    inputs.property("generatorClass", generatorClassProvider)
    inputs.property("includesTestEmitterFixtures", includesNodeFixturesProvider)
    inputs.property("emitterAcceptsEmitShared", acceptsEmitSharedProvider)
    inputs.property("sharedOutputStyle", sharedStyleProvider)
    outputs.dir(outDirProvider).withPropertyName("generatedUpdater")

    doLast {
        val language = languageProvider.get()
        val packageName = packageProvider.get()
        val emitterClass = emitterClassProvider.get()
        val generatorClass = generatorClassProvider.get()
        val includesNodeFixtures = includesNodeFixturesProvider.get()
        val acceptsEmitShared = acceptsEmitSharedProvider.get()
        val sharedStyle = sharedStyleProvider.get()
        require(sharedStyle == "generator" || sharedStyle == "elements") {
            "emitterFixtures.sharedOutputStyle must be \"generator\" or \"elements\", was \"$sharedStyle\""
        }

        val outFile = outDirProvider.get().asFile
            .resolve(packageName.replace('.', '/'))
            .resolve("UpdateEmitterFixtures.kt")
        outFile.parentFile.mkdirs()

        val emitterCtor = if (acceptsEmitShared) "$emitterClass(emitShared = EmitShared(true))" else "$emitterClass()"
        val sharedBody = when (sharedStyle) {
            "generator" -> "$emitterCtor.emitShared()\n    ?.let(${generatorClass.substringAfterLast('.')}::generate)\n    ?: error(\"Shared emit returned null\")"
            "elements" -> "$emitterCtor.emitShared()\n    ?.elements\n    ?.filterIsInstance<RawElement>()\n    ?.joinToString(\"\") { it.code }\n    ?: error(\"Shared emit returned null\")"
            else -> error("unreachable")
        }

        val imports = mutableListOf(
            "arrow.core.nonEmptyListOf",
            "arrow.core.nonEmptySetOf",
            "community.flock.wirespec.compiler.core.EmitContext",
            "community.flock.wirespec.compiler.core.FileUri",
            "community.flock.wirespec.compiler.core.parse.ast.AST",
            "community.flock.wirespec.compiler.core.parse.ast.Definition",
            "community.flock.wirespec.compiler.core.parse.ast.Module",
            "community.flock.wirespec.compiler.test.CompileChannelTest",
            "community.flock.wirespec.compiler.test.CompileComplexModelTest",
            "community.flock.wirespec.compiler.test.CompileEnumTest",
            "community.flock.wirespec.compiler.test.CompileFullEndpointTest",
            "community.flock.wirespec.compiler.test.CompileMinimalEndpointTest",
            "community.flock.wirespec.compiler.test.CompileNestedTypeTest",
            "community.flock.wirespec.compiler.test.CompileRefinedTest",
            "community.flock.wirespec.compiler.test.CompileTypeTest",
            "community.flock.wirespec.compiler.test.CompileUnionTest",
            "community.flock.wirespec.compiler.test.Fixture",
            "community.flock.wirespec.compiler.utils.NoLogger",
            "java.io.File",
        )
        if (acceptsEmitShared) imports += "community.flock.wirespec.compiler.core.emit.EmitShared"
        if (sharedStyle == "elements") imports += "community.flock.wirespec.ir.core.RawElement"
        if (sharedStyle == "generator") imports += generatorClass
        if (includesNodeFixtures) imports += "community.flock.wirespec.compiler.test.NodeFixtures"
        imports.sort()

        val sb = StringBuilder()
        sb.appendLine("// AUTO-GENERATED — do not edit. Source: emitterFixtures { ... } in build.gradle.kts.")
        sb.appendLine("@file:Suppress(\"ktlint\")")
        sb.appendLine("package $packageName")
        sb.appendLine()
        imports.forEach { sb.appendLine("import $it") }
        sb.appendLine()
        sb.appendLine("private const val LANGUAGE = \"$language\"")
        sb.appendLine()
        sb.appendLine("private val emitContext = object : EmitContext, NoLogger {")
        sb.appendLine("    override val emitters = nonEmptySetOf($emitterClass())")
        sb.appendLine("}")
        sb.appendLine()
        sb.appendLine("private fun emitNode(node: Definition): String {")
        sb.appendLine("    val ast = AST(nonEmptyListOf(Module(FileUri(\"\"), nonEmptyListOf(node))))")
        sb.appendLine("    return emitContext.emitters.first().emit(ast, emitContext.logger).first().result")
        sb.appendLine("}")
        sb.appendLine()
        sb.appendLine("private fun compile(fixture: Fixture): String = fixture.compiler { $emitterClass() }.fold(")
        sb.appendLine("    { error(\"Failed to compile fixture: \$it\") },")
        sb.appendLine("    { it },")
        sb.appendLine(")")
        sb.appendLine()
        sb.appendLine("private fun shared(): String = $sharedBody")
        sb.appendLine()
        sb.appendLine("fun main(args: Array<String>) {")
        sb.appendLine("    require(args.isNotEmpty()) { \"Usage: UpdateEmitterFixtures <fixturesRootDir>\" }")
        sb.appendLine("    val root = File(args[0])")
        sb.appendLine("    root.mkdirs()")
        sb.appendLine()
        sb.appendLine("    val fixtures: Map<String, () -> String> = linkedMapOf(")
        if (includesNodeFixtures) {
            sb.appendLine("        \"testEmitterType\" to { emitNode(NodeFixtures.type) },")
            sb.appendLine("        \"testEmitterEmptyType\" to { emitNode(NodeFixtures.emptyType) },")
            sb.appendLine("        \"testEmitterRefined\" to { emitNode(NodeFixtures.refined) },")
            sb.appendLine("        \"testEmitterEnum\" to { emitNode(NodeFixtures.enum) },")
        }
        sb.appendLine("        \"compileFullEndpointTest\" to { compile(CompileFullEndpointTest) },")
        sb.appendLine("        \"compileChannelTest\" to { compile(CompileChannelTest) },")
        sb.appendLine("        \"compileEnumTest\" to { compile(CompileEnumTest) },")
        sb.appendLine("        \"compileMinimalEndpointTest\" to { compile(CompileMinimalEndpointTest) },")
        sb.appendLine("        \"compileRefinedTest\" to { compile(CompileRefinedTest) },")
        sb.appendLine("        \"compileUnionTest\" to { compile(CompileUnionTest) },")
        sb.appendLine("        \"compileTypeTest\" to { compile(CompileTypeTest) },")
        sb.appendLine("        \"compileNestedTypeTest\" to { compile(CompileNestedTypeTest) },")
        sb.appendLine("        \"compileComplexModelTest\" to { compile(CompileComplexModelTest) },")
        sb.appendLine("        \"sharedOutputTest\" to { shared() },")
        sb.appendLine("    )")
        sb.appendLine()
        sb.appendLine("    fixtures.forEach { (name, produce) ->")
        sb.appendLine("        val target = root.resolve(name).resolve(\"\$LANGUAGE.txt\")")
        sb.appendLine("        target.parentFile.mkdirs()")
        sb.appendLine("        target.writeText(produce())")
        sb.appendLine("        println(\"[\$LANGUAGE] wrote \${target.absolutePath}\")")
        sb.appendLine("    }")
        sb.appendLine("}")
        outFile.writeText(sb.toString())
    }
}

// -------------- updateEmitterFixtures (run the generated main) --------------

tasks.register<JavaExec>("updateEmitterFixtures") {
    description = "Run the emitter and overwrite the shared fixture files for this language."
    group = "verification"

    val jvmTest = tasks.named<Test>("jvmTest")
    classpath = files(jvmTest.map { it.classpath })
    mainClass.set(ext.emitterPackage.map { "$it.UpdateEmitterFixturesKt" })
    args(fixturesSourceDir.absolutePath)

    dependsOn(jvmTest.map { it.dependsOn })
    outputs.upToDateWhen { false }
}
