name: 'Version number'
description: 'Check if version number is correct'
inputs:
  version:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  version:
    description: 'Version number'
    value: ${{ steps.version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - id: version
      name: Version number
      shell: bash
      run: |
        if [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
        then
        echo "version number valid: ${{ inputs.version }}"
        version="${{ inputs.version }}"
        version=${version:1}
        echo "version=$version"
        echo "version=$version" >> $GITHUB_OUTPUT
        exit 0
        else
        echo "version number not valid: ${{ inputs.version }}"
        echo "Please make sure version number matches: ^v[0-9]\.[0-9]\.[0-9]$"
        exit 1
        fi
