package community.flock.wirespec.examples.maven.spring.kotlin

import community.flock.wirespec.generated.examples.spring.kotlin.endpoint.GetGreeting
import community.flock.wirespec.generated.examples.spring.kotlin.model.Greeting
import org.springframework.web.bind.annotation.RestController

/**
 * Implements the Wirespec-generated [GetGreeting.Handler]. The handler interface,
 * the request/response types and the [Greeting] model are all generated by the
 * SpringKotlinEmitter and compiled by Kotlin 2.0 against the `spring-jvm`
 * integration — which is exactly what this example verifies.
 */
@RestController
class GreetingController : GetGreeting.Handler {
    override suspend fun getGreeting(request: GetGreeting.Request): GetGreeting.Response<*> =
        GetGreeting.Response200(Greeting(message = "Hello from Kotlin 2.0"))
}
