package community.flock.wirespec.integration.kotest.runtime

import io.kotest.property.Arb
import io.kotest.property.arbitrary.Codepoint
import io.kotest.property.arbitrary.alphanumeric
import io.kotest.property.arbitrary.boolean
import io.kotest.property.arbitrary.byte
import io.kotest.property.arbitrary.char
import io.kotest.property.arbitrary.double
import io.kotest.property.arbitrary.float
import io.kotest.property.arbitrary.int
import io.kotest.property.arbitrary.long
import io.kotest.property.arbitrary.short
import io.kotest.property.arbitrary.string

/**
 * Default kotest [Arb]s for the primitive types that appear as path / query /
 * header fields, used to auto-generate a slot the caller did not override with a
 * [io.kotest.property.Gen]. Bodies are generated by the Wirespec generator instead,
 * so they never reach this resolver.
 *
 * Keyed by the field's reflected Java [Class], which may be a JVM primitive (`int`)
 * for a non-null Kotlin field or its boxed form (`Integer`) for a nullable one —
 * both are mapped.
 */
internal object PrimitiveArbs {
    /** Whether [forType] can supply a default generator for [type] (i.e. it is a known primitive/String). */
    fun supports(type: Class<*>): Boolean = runCatching { forType(type) }.isSuccess

    fun forType(type: Class<*>): Arb<*> = when (type) {
        // Alphanumeric + non-empty so an auto-generated value is safe to drop into a
        // URL path segment (no `/`, no reserved characters) and never blank.
        String::class.java -> Arb.string(minSize = 1, maxSize = 20, codepoints = Codepoint.alphanumeric())
        Int::class.javaPrimitiveType, Integer::class.java -> Arb.int()
        Long::class.javaPrimitiveType, java.lang.Long::class.java -> Arb.long()
        Short::class.javaPrimitiveType, java.lang.Short::class.java -> Arb.short()
        Byte::class.javaPrimitiveType, java.lang.Byte::class.java -> Arb.byte()
        Boolean::class.javaPrimitiveType, java.lang.Boolean::class.java -> Arb.boolean()
        Double::class.javaPrimitiveType, java.lang.Double::class.java -> Arb.double()
        Float::class.javaPrimitiveType, java.lang.Float::class.java -> Arb.float()
        Char::class.javaPrimitiveType, Character::class.java -> Arb.char()
        else -> error(
            "No default generator for path/query/header field type ${type.name}. Pass this field explicitly as a Gen.",
        )
    }
}
