name: Publish

on:
  push:
    branches:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate version
        id: version
        uses: ./.github/actions/version
        with:
          version: ${{ github.event.inputs.version }}
