name: Publish

on:
  push:
    branches:

env:
  VERSION: "v0.0.0"

jobs:

  version:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate version
        id: version
        uses: ./.github/actions/version
        with:
          version: ${{ env.VERSION }}

  test:
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - run: |
          echo "${{needs.version.steps.version.outputs.version}}"
    
