name: Publish

on:
  push:
    branches:

env:
  VERSION: "v0.0.0"

jobs:

  version:

    runs-on: ubuntu-latest

    outputs:
      version: ${{steps.version.outputs.version}}"

    steps:
      - uses: actions/checkout@v3
      - name: Generate version
        id: version
        uses: ./.github/actions/version
        with:
          version: ${{ env.VERSION }}
      - run: |
          echo "Hello: ${{steps.version.outputs.version}}"
  test:
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - run: |
          echo "Hello: ${{needs.version.outputs.version}}"
          exit 0
    
