name: Publish

on:
  push:
    branches:

env:
  VERSION: "v0.0.0"

jobs:

  version:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate version
        id: version
        run: |
          if [[ "${{ env.VERSION }}" =~ ^v[0-9]\.[0-9]\.[0-9]$ ]]
          then
          echo "version number valid: ${{ env.VERSION }}"
          version="${{ env.VERSION }}"
          version=${version:1}
          echo "version=$version"
          echo "version=123" >> $GITHUB_OUTPUT
          exit 0
          else
          echo "version number not valid: ${{ env.VERSION }}"
          echo "Please make sure version number matches: ^v[0-9]\.[0-9]\.[0-9]$"
          exit 1
          fi
      - run: |
          echo "Hello: ${{steps.version.outputs.version}}"
  test:
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - run: |
          echo "Hello: ${{needs.version.steps.version.outputs.version}}"
    
